
envvvv: prod

spring:
  #配置rabbitMQ,如果不配置，默认连接 guest@127.0.0.1:5672
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 配置zipkin服务
  zipkin:
    base-url: http://zipkin-server/         
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      # 即以100%的概率将链路的数据上传到Zipkin Server上，默认为0.1
      probability: 1.0  
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 总是显示完整的health 详情 
  endpoint:
    health:
      show-details: always         